### ISSUE TITLE
Weird character issues, possibly syntax highlighting bugging out.

### ISSUE THREAD

**Issue by leetNightshade** [marssaxman/ozette#36]
I imagine it's syntax highlighting, but there's strange characters showing up in my MSys2 terminal on Windows 10. 

![2018_06_27_11_26_30_ozette_home_ln_projects_warp_warpengine_warpengine_code_example](https://user-images.githubusercontent.com/40641737/41992364-194a406e-79fd-11e8-9475-1e62cf173448.png)

**Comment by leetNightshade** [comment]
I was considering forking this project to extend it for my needs until I ran into this issue. I'm not sure what it is but I don't want to spend time looking into it myself if I can find another editor that works well.

**Comment by leetNightshade** [comment]
On CMDER on Windows 10 the issues are even worse and the vertical lines don't line up.

**Comment by marssaxman** [comment]
I am suspicious of a text-encoding issue. I notice that the red highlighting on the comment which is the first line inside SpaceChasers::Load() only covers half the characters. That makes me suspicious that this file might be encoded in UTF-16. In that case ozette might well ignore all the null bytes, so that ASCII-range codepoints would appear to display correctly, but it would attempt to decode non-ASCII chars as UTF-8 codepoints, leading to all the garbage.

Ozette doesn't have a good story about Unicode yet; its text engine handles UTF-8, but I haven't updated the display interface to use 'ncursesw' instead of 'ncurses', so it's effectively still an ASCII-only editor at this point.
